create extension if not exists pgcrypto;

create table if not exists public.work_settings (
  id text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.work_users (
  id uuid primary key default gen_random_uuid(),
  login_id text not null unique,
  password text not null,
  display_name text not null,
  role text not null default 'worker' check (role in ('admin', 'worker')),
  team_no integer check (team_no is null or team_no >= 0),
  region_no integer check (region_no is null or region_no >= 0),
  worker_type text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.work_users add column if not exists password text;
alter table public.work_users add column if not exists team_no integer;
alter table public.work_users add column if not exists region_no integer;
alter table public.work_users add column if not exists worker_type text;
alter table public.work_users drop constraint if exists work_users_team_no_check;
alter table public.work_users add constraint work_users_team_no_check check (team_no is null or team_no >= 0);
alter table public.work_users drop constraint if exists work_users_region_no_check;
alter table public.work_users add constraint work_users_region_no_check check (region_no is null or region_no >= 0);

create table if not exists public.work_records (
  id bigint generated by default as identity primary key,
  work_date date not null,
  team_no integer not null check (team_no > 0),
  period text not null check (period in ('morning', 'afternoon')),
  work_type text not null check (work_type in ('joint', 'move', 'existing')),
  actual_qty integer not null default 0 check (actual_qty >= 0),
  updated_by uuid,
  updated_at timestamptz not null default now(),
  unique (work_date, team_no, period, work_type)
);

alter table public.work_records drop constraint if exists work_records_updated_by_fkey;
alter table public.work_records
  add constraint work_records_updated_by_fkey
  foreign key (updated_by) references public.work_users(id) on delete set null;

alter table public.work_settings enable row level security;
alter table public.work_users enable row level security;
alter table public.work_records enable row level security;

grant select, insert, update on table public.work_settings to anon, authenticated;
grant select, insert, update on table public.work_records to anon, authenticated;
grant usage, select on sequence public.work_records_id_seq to anon, authenticated;

revoke all on table public.work_users from anon, authenticated;

drop policy if exists "App can read settings" on public.work_settings;
drop policy if exists "App can write settings" on public.work_settings;
drop policy if exists "App can read records" on public.work_records;
drop policy if exists "App can insert records" on public.work_records;
drop policy if exists "App can update records" on public.work_records;

create policy "App can read settings"
  on public.work_settings for select
  to anon, authenticated
  using (true);

create policy "App can write settings"
  on public.work_settings for all
  to anon, authenticated
  using (true)
  with check (true);

create policy "App can read records"
  on public.work_records for select
  to anon, authenticated
  using (true);

create policy "App can insert records"
  on public.work_records for insert
  to anon, authenticated
  with check (true);

create policy "App can update records"
  on public.work_records for update
  to anon, authenticated
  using (true)
  with check (true);

drop function if exists public.work_login(text, text);

create function public.work_login(
  p_login_id text,
  p_password text
)
returns table (
  user_id uuid,
  login_id text,
  display_name text,
  role text,
  team_no integer,
  region_no integer,
  worker_type text
)
language sql
security definer
set search_path = public
as $$
  select
    id,
    work_users.login_id,
    work_users.display_name,
    work_users.role,
    work_users.team_no,
    work_users.region_no,
    work_users.worker_type
  from public.work_users
  where work_users.login_id = p_login_id
    and work_users.is_active = true
    and work_users.password = p_password
  limit 1;
$$;

revoke all on function public.work_login(text, text) from public;
grant execute on function public.work_login(text, text) to anon, authenticated;

insert into public.work_settings (id, value)
values ('default', '{"teamCount": 4}'::jsonb)
on conflict (id) do update
set value = excluded.value,
    updated_at = now();

-- 사용자 생성 예시입니다. password에는 숫자/문자 비밀번호가 그대로 저장됩니다.
-- insert into public.work_users (login_id, password, display_name, role, team_no, region_no, worker_type)
-- values ('worker01', '1001', '작업자01', 'worker', 1, 1, '모뎀작업자');
--
-- insert into public.work_users (login_id, password, display_name, role, team_no, region_no, worker_type)
-- values ('admin', '9999', '관리자', 'admin', 0, 0, '관리자');
